include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: false
    constant_identifier_names: false
    overridden_fields: false
    use_build_context_synchronously: false
