name: baby_growth_tracker
description: Baby Growth Tracker App.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  provider: ^6.0.4
  auto_route: ^5.0.4
  google_nav_bar: ^5.0.6
  flutter_snake_navigationbar: ^0.6.1
  image_picker: ^0.7.2+1
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.0
  image_cropper: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  auto_route_generator: ^5.0.3


flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/icons/
    - assets/images/