name: baby_growth_tracker
description: Baby Growth Tracker App.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  provider: ^6.0.4
  auto_route: ^5.0.2
  google_nav_bar: ^5.0.6
  flutter_snake_navigationbar: ^0.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  auto_route_generator: ^5.0.3


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/