name: baby_growth_tracker
description: Baby Growth Tracker App.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #Icons
  cupertino_icons: ^1.0.2

  #State Management
  provider: ^6.0.4

  #Routing
  auto_route: ^5.0.4

  #Localization
  easy_localization: ^3.0.2

  #Caching
  shared_preferences: ^2.1.0

  #Utils
  flutter_snake_navigationbar: ^0.6.1
  flutter_spinkit: ^5.1.0
  image_picker: ^1.0.0
  image_cropper: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  auto_route_generator: ^5.0.3


flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/icons/
    - assets/images/